import img1 from "@/assets/flashImag/product-img2.png";
import offerImg1 from "@/assets/offerImag/offer-img1.png";
import offerImg2 from "@/assets/offerImag/offer-img2.png";
import offerlogo from "@/assets/offerImag/offer-logo.png";

import hotDeal1 from "@/assets/hotDeals/product-img1.png";
import hotDeal2 from "@/assets/hotDeals/product-img2.png";
import hotDeal3 from "@/assets/hotDeals/product-img3.png";
import hotDeal4 from "@/assets/hotDeals/product-img4.png";

import dailyBestSell1 from "@/assets/dailyBestSell/best-sell1.png";
import dailyBestSell2 from "@/assets/dailyBestSell/best-sell2.png";
import dailyBestSell3 from "@/assets/dailyBestSell/best-sell3.png";
import dailyBestSell4 from "@/assets/dailyBestSell/best-sell4.png";

import orgFood1 from "@/assets/orgaanicFood/product-img20.png";
import orgFood2 from "@/assets/orgaanicFood/product-img21.png";
import orgFood3 from "@/assets/orgaanicFood/product-img22.png";
import orgFood4 from "@/assets/orgaanicFood/product-img23.png";
import orgFood5 from "@/assets/orgaanicFood/product-img24.png";
import orgFood6 from "@/assets/orgaanicFood/product-img25.png";

export const vegitableProduct = [
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 20,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: img1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
];

export const offerProduct = [
  {
    image: offerImg1,
    offer: 5,
    offerLogo: offerlogo,
  },
  {
    image: offerImg2,
    offer: 8,
    offerLogo: offerlogo,
  },
];

export const hotDealsToday = [
  {
    title: "Marcels Modern Pentry Almond",
    marketName: "By Lucky Supermarket",
    image: hotDeal1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 26,
  },
  {
    title: "Whole Grains and Seeds Organic Bread",
    marketName: "By Lucky Supermarket",
    image: hotDeal2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 30,
  },
  {
    title: "O Organic Milck Whole Vitamin D",
    marketName: "By Lucky Supermarket",
    image: hotDeal3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 45,
  },
  {
    title: "Tropicana 100% juice, Organs no Polp",
    marketName: "By Lucky Supermarket",
    image: hotDeal4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 25,
  },
  {
    title: "Tropicana 100% juice, Organs no Polp",
    marketName: "By Lucky Supermarket",
    image: hotDeal4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 25,
  },
];

export const dailyBestSell = [
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: dailyBestSell1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 26,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: dailyBestSell2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 30,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: dailyBestSell3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 45,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: dailyBestSell4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 25,
  },
];

export const organicProduct = [
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood6,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 20,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood5,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
];

export const shopProduct = [
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood6,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 26,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 45,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Snacks",
    image: orgFood5,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Snacks",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood6,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 20,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood5,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood6,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Vegitables",
    image: orgFood1,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 20,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood2,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood4,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood5,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
  {
    title: "Tailor Farms Broccoli Florets Vegitables",
    marketName: "By Lucky Supermarket",
    category: "Fruits",
    image: orgFood3,
    rating: 4.8,
    price: 40.89,
    quantity: 50,
    sold: 13,
  },
];
